#:schema node_modules/wrangler/config-schema.json
name = "sublink-worker-xin"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "47e9ba343d8a427c934b64e03deb9176" }
]
